apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    k8s-app/opster.io: metricbeat-opster
  name: metricbeat-opster
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app/opster.io: metricbeat-opster
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app/opster.io: metricbeat-opster
    spec:
      containers:
      - env:
        - name: OPSTER_TOKEN
          valueFrom:
            secretKeyRef:
              name: opster-secret
              key: opster-token
        - name: ES_URL
          valueFrom:
            secretKeyRef:
              name: opster-secret
              key: es-url
        - name: OPSTER_PORT
          valueFrom:
            secretKeyRef:
              name: opster-secret
              key: opster-port
        image: public.ecr.aws/opsterio/opster-metricbeat:arm64-latest
        imagePullPolicy: Always
        name: metricbeat-opster
        securityContext:
          runAsUser: 1000
      restartPolicy: Always
